[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["grimmer <grimmer0125@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.3.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

